In [15]:
from keras.datasets import cifar10
import numpy as np

# load the data
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
y_train = np.squeeze(y_train)
print('data loaded')

data loaded


In [16]:
print( "Shape of train features: ", np.shape(x_train), "Shape of test features: ", np.shape(x_test))
print("The data is in 3D arrays")

Shape of train features:  (50000, 32, 32, 3) Shape of test features:  (10000, 32, 32, 3)
The data is in 3D arrays


In [17]:
print("In the training data there are 10 classes of object, each contains 5000 examples")
np.unique(y_train, return_counts=True)

In the training data there are 10 classes of object, each contains 5000 examples


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]))

In [18]:
print("In the test data there are 10 classes of object, each contains 1000 examples")
np.unique(y_test, return_counts=True)

In the test data there are 10 classes of object, each contains 1000 examples


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]))

## Random predictions

In [25]:
def cifar_10_rand(x) :
    size = len(x)
    random_preds = np.random.randint(0, 10, size)
    return random_preds

In [26]:
rand_preds = cifar_10_rand(x_test)

In [27]:
# let's see what's inside
rand_preds[0:100]

array([1, 9, 1, 6, 1, 7, 2, 9, 5, 4, 0, 4, 1, 5, 9, 4, 7, 6, 4, 4, 9, 7,
       2, 1, 4, 5, 0, 7, 9, 2, 0, 5, 0, 8, 7, 8, 8, 8, 3, 7, 7, 0, 5, 4,
       8, 8, 2, 1, 2, 0, 2, 0, 8, 3, 5, 4, 5, 5, 8, 5, 6, 9, 2, 3, 5, 2,
       9, 8, 3, 2, 5, 7, 4, 4, 0, 1, 6, 3, 6, 1, 4, 7, 1, 5, 4, 1, 1, 2,
       3, 4, 2, 2, 5, 6, 6, 0, 8, 5, 1, 0])

## Accuracy function

In [28]:
def getAccuracy(testSet, predictions):
    correct = 0
    for x in range(len(testSet)):
        if testSet[x][-1] == predictions[x]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [29]:
score = getAccuracy(y_test, rand_preds)
print( "The accuracy score for random prediction model is: ", score, "%")

The accuracy score for random prediction model is:  9.950000000000001 %


## The kNN model

The data needs to be reshaped from 3D to 2D numpy array

In [10]:
d1, d2, d3, d4 = x_train.shape
train_reshaped = x_train.reshape((d1, d2*d3*d4))

d1, d2, d3, d4 = x_test.shape
test_reshaped = x_test.reshape((d1, d2*d3*d4))

print(np.shape(train_reshaped), np.shape(test_reshaped))

(50000, 3072) (10000, 3072)


We'll take a small part of the data for the test

In [31]:
train1 = train_reshaped[0:100, :]
Y_train1 = y_train[0:100]
test1 = test_reshaped[0:10, :]
Y_test1 = y_test[0:10]

In [32]:
import math
import operator

def euclideanDistance(instance1, instance2, length):
    distance = 0
    for x in range(length):
        distance += pow((instance1[x] - instance2[x]), 2)
    return math.sqrt(distance)


distances = []
for x in range(len(train1)):
    for i in range(len(test1)):
        distances.append(euclideanDistance(train1[x], test1[i], len(train1)))

distances = np.array(distances)
distances = distances.reshape(10, 100)

/Users/anna/miniconda3/envs/main/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in ubyte_scalars
  import sys


In [34]:
responses = []
for i in range(len(distances)):
    nearest = np.argmin(distances[i])
    response = Y_train1[nearest]
    responses.append(response)
print(responses)

[3, 9, 7, 7, 3, 8, 7, 3, 5, 7]


In [35]:
print(Y_test1)

[[3]
 [8]
 [8]
 [0]
 [6]
 [6]
 [1]
 [6]
 [3]
 [1]]


In [37]:
getAccuracy(Y_test1, responses)

10.0